package dev.apkforge.bridge;

import org.json.JSONObject;
import java.lang.reflect.Method;

/** Executes against the actual retained model classes, not reimplemented models. */
public final class ModelContractProbe {
    private static Object gson;
    private static Method deserialize;
    private static Object decode(String name,JSONObject json)throws Exception {
        return deserialize.invoke(gson,json.toString(),Class.forName(name));
    }
    private static Object call(Object value,String method)throws Exception {return value.getClass().getMethod(method).invoke(value);}
    private static Object decodeComment(JSONObject data)throws Exception {
        java.text.SimpleDateFormat format=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ",java.util.Locale.US);
        Object adapter=Class.forName("com.ellation.crunchyroll.api.DateTypeAdapter").getConstructor(java.text.SimpleDateFormat.class,java.text.SimpleDateFormat.class,java.text.SimpleDateFormat.class).newInstance(format,format,new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",java.util.Locale.US));
        Object builder=Class.forName("com.google.gson.GsonBuilder").getConstructor().newInstance();
        builder.getClass().getMethod("registerTypeAdapter",java.lang.reflect.Type.class,Object.class).invoke(builder,java.util.Date.class,adapter);
        Object talkbox=builder.getClass().getMethod("create").invoke(builder);
        return talkbox.getClass().getMethod("fromJson",String.class,Class.class).invoke(talkbox,data.toString(),Class.forName("com.ellation.crunchyroll.api.etp.commenting.model.Comment"));
    }
    private static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    public static void main(String[] args)throws Exception {
        Thread.setDefaultUncaughtExceptionHandler((thread,error)->{Throwable cause=error;for(int depth=0;depth<16&&cause.getCause()!=null&&cause.getCause()!=cause;depth++)cause=cause.getCause();System.err.println("Native probe failure: "+cause.getClass().getSimpleName()+": "+String.valueOf(cause.getMessage()).replaceAll("https?://\\S+","[url]"));for(StackTraceElement frame:error.getStackTrace())if(frame.getClassName().startsWith("dev.apkforge."))System.err.println("  at "+frame);System.exit(1);});
        if(android.os.Looper.getMainLooper()==null)android.os.Looper.prepareMainLooper();
        gson=Class.forName("com.ellation.crunchyroll.api.GsonHolder").getMethod("getInstance").invoke(null);
        deserialize=gson.getClass().getMethod("fromJson",String.class,Class.class);
        int checks=0;
        for(String rating:new String[]{"","UP","DOWN","NONE"}){
            Object model=decode("com.ellation.crunchyroll.api.etp.contentreviews.model.episode.EpisodeRatingContainer",NativeRatings.container(true,rating));
            Object up=call(model,"getUp"),down=call(model,"getDown");
            check(up!=null&&down!=null,"Episode rating stats must exist for the retained player");
            check(((Number)call(up,"getRawRatingCount")).intValue()==(rating.equals("UP")?1:0),"Wrong up count");
            check(((Number)call(down,"getRawRatingCount")).intValue()==(rating.equals("DOWN")?1:0),"Wrong down count");
            check(call(model,"getUserContentRating").toString().equals(rating.equals("UP")||rating.equals("DOWN")?rating:"NONE"),"Wrong episode rating enum");checks++;
        }
        for(String rating:new String[]{"","1s","5s"}){
            Object model=decode("com.ellation.crunchyroll.api.etp.contentreviews.model.ContentRatingContainer",NativeRatings.container(false,rating));
            for(String method:new String[]{"getOneStar","getTwoStars","getThreeStars","getFourStars","getFiveStars"})check(call(model,method)!=null,"Missing series stats");
            check(((Number)call(model,"getAverage")).intValue()==(rating.isEmpty()?0:Integer.parseInt(rating.substring(0,1))),"Wrong series average");checks++;
        }
        JSONObject title=new JSONObject().put("anilistId",154587).put("title","Contract fixture").put("poster","https://example.invalid/poster.jpg")
            .put("episodes",new JSONObject().put("total",28).put("sub",28).put("dub",28));
        Object panel=decode("com.ellation.crunchyroll.model.Panel",BackendBridge.panel(title));
        check(call(panel,"getResourceType").toString().equals("series"),"Panel must be navigable by original screen");
        Object images=call(panel,"getImages");java.util.List<?> wide=(java.util.List<?>)call(images,"getPostersWide");
        Object image=wide.get(0);check(((Number)call(image,"getWidth")).intValue()==1280&&((Number)call(image,"getHeight")).intValue()==720,"Wide hero presentation ratio");checks++;
        Object book=decode("com.ellation.crunchyroll.api.etp.commenting.model.Guestbook",NativeCommunity.route(android.net.Uri.parse("https://local/talkbox/guestbooks/ANI269E1"),"GET"));
        check(call(book,"getGuestbookKey").equals("ANI269E1")&&((Number)call(book,"getTotalComments")).intValue()==0,"Empty replacement guestbook contract");checks++;
        Object comments=decode("com.ellation.crunchyroll.api.etp.commenting.model.CommentPreview",NativeCommunity.route(android.net.Uri.parse("https://local/talkbox/guestbooks/ANI269E1/comments"),"GET"));
        check(((java.util.List<?>)call(comments,"getComments")).isEmpty()&&((Number)call(comments,"getTotal")).intValue()==0,"Empty replacement comment preview contract");checks++;
        try{NativeCommunity.route(android.net.Uri.parse("https://local/talkbox/guestbooks/ANI269E1/comments"),"POST");throw new AssertionError("Must not pretend to save comments");}
        catch(BackendBridge.HttpFailure expected){check(expected.status==501,"Explicit unsupported community write");checks++;}
        JSONObject lists=new JSONObject();android.net.Uri listsUri=android.net.Uri.parse("https://local/content/v2/local/custom-lists");
        JSONObject created=NativeLists.route(lists,listsUri,"POST",new JSONObject().put("title","Native contract list"));
        JSONObject record=created.getJSONArray("data").getJSONObject(0);String listId=record.getString("list_id");
        Object createdModel=decode("com.ellation.crunchyroll.api.etp.content.model.customlists.CreatedCustomList",record);
        check(call(createdModel,"getListId").equals(listId)&&call(createdModel,"getModifiedAt")!=null,"Created list date/id contract");checks++;
        Object listsModel=decode("com.ellation.crunchyroll.api.etp.content.model.customlists.CustomLists",NativeLists.route(lists,listsUri,"GET",new JSONObject()));
        check(((java.util.List<?>)call(listsModel,"getItems")).size()==1&&((Number)call(call(listsModel,"getMetadata"),"getMaxPrivate")).intValue()==10,"List collection metadata contract");checks++;
        android.net.Uri listUri=android.net.Uri.parse(listsUri+"/"+listId);
        NativeLists.route(lists,listUri,"PATCH",new JSONObject().put("title","Renamed"));
        Object itemsModel=decode("com.ellation.crunchyroll.api.etp.content.model.customlists.CustomListItems",NativeLists.route(lists,listUri,"GET",new JSONObject()));
        check(((java.util.List<?>)call(itemsModel,"getItems")).isEmpty()&&call(call(itemsModel,"getMetadata"),"getTitle").equals("Renamed"),"Empty list detail and rename contract");checks++;
        try{NativeLists.route(lists,listsUri,"POST",new JSONObject().put("title"," "));throw new AssertionError("Invalid title must fail");}
        catch(BackendBridge.HttpFailure expected){check(expected.status==400&&lists.length()==1,"Invalid title must not mutate lists");checks++;}
        NativeLists.route(lists,listUri,"DELETE",new JSONObject());check(lists.length()==0,"Delete list contract");checks++;
        JSONObject providerEpisode=new JSONObject().put("number",1).put("runtimeSeconds",1431).put("available",new JSONObject().put("sub",true).put("dub",true));
        Object episodeModel=decode("com.ellation.crunchyroll.model.Episode",NativeCatalog.episode(title,providerEpisode));
        check(call(episodeModel,"getOriginalAudio").equals("ja-JP")&&((java.util.List<?>)call(episodeModel,"getVersions")).size()==2,"Selectable audio versions prevent locale reload loop");checks++;
        title.put("episodeList",new org.json.JSONArray().put(providerEpisode).put(new JSONObject(providerEpisode.toString()).put("number",2)));
        java.lang.reflect.Field cache=BackendBridge.class.getDeclaredField("titles");cache.setAccessible(true);
        @SuppressWarnings("unchecked") java.util.Map<Integer,JSONObject> cached=(java.util.Map<Integer,JSONObject>)cache.get(null);cached.put(154587,title);
        JSONObject next=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/discover/up_next/ANI154587E1"));
        check(next.getJSONArray("data").getJSONObject(0).getJSONObject("panel").getString("id").equals("ANI154587E2"),"Next episode must not point back to itself");checks++;
        check(NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/discover/up_next/ANI154587E2")).getJSONArray("data").length()==0,"End of series must have no next episode");checks++;
        Object dubbed=decode("com.ellation.crunchyroll.model.Episode",NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/episodes/ANI154587E1D")).getJSONArray("data").getJSONObject(0));
        check(call(dubbed,"getAudioLocale").equals("en-US")&&call(dubbed,"getId").equals("ANI154587E1D"),"Dubbed asset locale/id must agree");checks++;
        Object watchlistPanel=decode("com.ellation.crunchyroll.model.Panel",NativeCatalog.watchlistPanel(title));
        check(call(watchlistPanel,"getResourceType").toString().equals("episode")&&call(call(watchlistPanel,"getPanelMetadata"),"getParentId").equals("ANI154587"),"Watchlist row must expose episode image and series parent");checks++;
        check(BackendBridge.replacementHost("cr-play-service.prd.crunchyrollsvc.com"),"Native player uses a separate original service hostname");checks++;
        check(!BackendBridge.replacementHost("crunchyroll.com.example.invalid")&&!BackendBridge.replacementHost(null),"Replacement must not intercept unrelated domains");checks++;
        org.json.JSONArray records=new org.json.JSONArray().put(title).put(title).put(new JSONObject(title.toString()).put("anilistId",99).put("adult",true));
        Object feed=decode("com.ellation.crunchyroll.api.model.HomeFeedItemRaw",NativeHomeFeed.collection("popular","Popular This Week",records));
        check((Boolean)call(feed,"isValid")&&call(feed,"getResourceType").toString().equals("CURATED_COLLECTION")&&call(feed,"getResponseType").toString().equals("SERIES"),"Original Home collection model");
        check(((java.util.List<?>)call(feed,"getItemsIds")).size()==1&&call(feed,"getLink").equals("/content/v2/discover/apkforge-popular"),"Home must deduplicate records and exclude adult titles");checks++;
        check(NativeHomeFeed.query("popular").contains("range=week")&&NativeHomeFeed.query("movies").contains("format=MOVIE"),"View All must use the same collection filters");checks++;
        try{NativeHomeFeed.query("unknown");throw new AssertionError("Unknown collection must fail");}catch(BackendBridge.HttpFailure expected){check(expected.status==404,"Unknown collection status");checks++;}
        JSONObject seasonalTags=NativeHomeFeed.seasonalTags();
        JSONObject seasonal=seasonalTags.getJSONArray("data").getJSONObject(0);
        check(seasonal.getString("id").equals("current")&&seasonal.getJSONObject("localization").getString("title").equals("Currently Airing"),"Simulcast season tag must expose a resolvable live tag");checks++;
        check(NativeHomeFeed.seasonalQuery("current").contains("range=today"),"Simulcast tag must use the live provider collection");checks++;
        org.json.JSONArray feedRows=new org.json.JSONArray().put(new JSONObject().put("id","hero")).put(new JSONObject().put("id","row-1")).put(new JSONObject().put("id","row-2"));
        JSONObject firstPage=NativeHomeFeed.page(feedRows,0,2),secondPage=NativeHomeFeed.page(feedRows,2,2);
        check(firstPage.getJSONArray("data").length()==2&&secondPage.getJSONArray("data").length()==1&&secondPage.getJSONArray("data").getJSONObject(0).getString("id").equals("row-2"),"Scrolling must not repeat the hero or earlier rows");checks++;
        check(firstPage.getInt("total")==3&&secondPage.getInt("total")==3&&NativeHomeFeed.page(feedRows,3,2).getJSONArray("data").length()==0,"Home total and empty final page must terminate pagination");checks++;
        check(NativeHomeFeed.page(feedRows,Integer.MAX_VALUE,Integer.MAX_VALUE).getJSONArray("data").length()==0&&NativeHomeFeed.page(feedRows,-1,0).getJSONArray("data").length()==1,"Home pagination bounds must not overflow or fail");checks++;
        java.util.Set<Integer> homeIds=new java.util.LinkedHashSet<>();
        org.json.JSONArray selected=NativeHomeFeed.select(records,homeIds,14);
        check(selected.length()==1&&homeIds.size()==1,"Home selection excludes repeated and adult cards");checks++;
        org.json.JSONArray other=NativeHomeFeed.select(new org.json.JSONArray().put(title).put(new JSONObject(title.toString()).put("anilistId",20)).put(new JSONObject(title.toString()).put("anilistId",21)),homeIds,1);
        check(other.length()==1&&other.getJSONObject(0).getInt("anilistId")==20&&!homeIds.contains(21),"Home rows exclude IDs from earlier rows without claiming unseen cards");checks++;
        java.lang.reflect.Field active=NativeHomeFeed.class.getDeclaredField("snapshot"),ready=NativeHomeFeed.class.getDeclaredField("refreshed"),expiry=NativeHomeFeed.class.getDeclaredField("expires");
        active.setAccessible(true);ready.setAccessible(true);expiry.setAccessible(true);
        active.set(null,feedRows);ready.set(null,new org.json.JSONArray().put(new JSONObject().put("id","new-hero")).put(new JSONObject().put("id","new-row-1")).put(new JSONObject().put("id","new-row-2")));expiry.setLong(null,Long.MAX_VALUE);
        check(NativeHomeFeed.home(2,2).getJSONArray("data").getJSONObject(0).getString("id").equals("row-2"),"Completed refresh must not replace an active scroll's later pages");checks++;
        check(NativeHomeFeed.home(0,2).getJSONArray("data").getJSONObject(0).getString("id").equals("new-hero")&&NativeHomeFeed.home(2,2).getJSONArray("data").getJSONObject(0).getString("id").equals("new-row-2"),"A new feed starts with the completed refresh and keeps coherent pagination");checks++;
        java.lang.reflect.Field pending=NativeHomeFeed.class.getDeclaredField("loading");pending.setAccessible(true);
        pending.set(null,new java.util.concurrent.FutureTask<org.json.JSONArray>(() -> {throw new AssertionError("Fixture refresh must not run");}));expiry.setLong(null,0);
        java.util.concurrent.ExecutorService caller=java.util.concurrent.Executors.newSingleThreadExecutor();
        try{check(caller.submit(() -> NativeHomeFeed.home(0,2)).get(1,java.util.concurrent.TimeUnit.SECONDS).getJSONArray("data").getJSONObject(0).getString("id").equals("new-hero"),"A warm Home must return the current page while a network refresh is pending");checks++;}
        finally{caller.shutdownNow();pending.set(null,null);active.set(null,null);ready.set(null,null);expiry.setLong(null,0);}
        JSONObject summary=new JSONObject(title.toString());summary.remove("episodeList");
        BackendBridge.cache(new org.json.JSONArray().put(summary));
        check(BackendBridge.series(154587).has("episodeList"),"Home summary refresh must retain loaded episodes");checks++;
        check(BackendBridge.series(154587).getJSONArray("episodeList")==title.getJSONArray("episodeList"),"Summary updates must preserve the loaded episode array without cloning it under the image-cache lock");checks++;
        check(call(watchlistPanel,"getStreamHref").equals("/apkforge/playback/ANI154587E1"),"A playable native Panel must retain its stream link");checks++;
        Object onlyDub=decode("com.ellation.crunchyroll.model.Episode",NativeCatalog.episode(title,new JSONObject(providerEpisode.toString()).put("available",new JSONObject().put("sub",false).put("dub",true))));
        check(call(onlyDub,"getAudioLocale").equals("en-US")&&call(onlyDub,"getId").equals("ANI154587E1D"),"Dub-only episodes must not advertise an unavailable Japanese asset");checks++;
        Class<?> premiumFlag=Class.forName("id0.a");
        Object guestFlag=java.lang.reflect.Proxy.newProxyInstance(premiumFlag.getClassLoader(),new Class<?>[]{premiumFlag},(self,method,arguments)->Boolean.FALSE);
        Object availability=Class.forName("ov.c").getConstructor(premiumFlag).newInstance(guestFlag);
        check(availability.getClass().getMethod("a",Class.forName("com.ellation.crunchyroll.model.PlayableAsset")).invoke(availability,episodeModel).equals("available"),"Provider-available episode must pass original date-based availability contract");checks++;
        JSONObject hlsJson=NativePlayback.streamJson("ANI21E1","https://example.invalid/master.m3u8","sub",
            new org.json.JSONArray().put(new JSONObject().put("format","vtt").put("language","en").put("file","https://example.invalid/en.vtt")));
        Object hls=decode("com.ellation.crunchyroll.api.cms.model.streams.Streams",hlsJson);
        Object nativePlayer=NativePlayback.mapHls("ANI21E1",hls,null,"");
        check(nativePlayer!=null&&nativePlayer.getClass().getField("d").get(nativePlayer).toString().equals("HLS"),"Original player must select HLS rather than DASH");
        check(nativePlayer.getClass().getField("e").get(nativePlayer).equals("https://example.invalid/master.m3u8")&&((java.util.List<?>)call(nativePlayer,"f")).size()==1,"Original URL and external subtitle mapping");
        check(nativePlayer.getClass().getField("g").get(nativePlayer)==null&&nativePlayer.getClass().getField("j").get(nativePlayer)==null,"Public HLS must not synthesize DRM tokens or licensed sessions");checks++;
        JSONObject emptyHls=new JSONObject(hlsJson.toString()).put("streams",new JSONObject());
        check(NativePlayback.mapHls("ANI21E1",decode("com.ellation.crunchyroll.api.cms.model.streams.Streams",emptyHls),null,"")==null,"Non-HLS streams retain original mapper");checks++;
        check(NativePlayback.decodeSources("wdeBruh3qqn_i5wUNnyaPYD8arCx-VSkn9ax1dWdZbr5zTx8zxHC6TDwg54JqrA1").getString("file").equals("https://example.invalid/master.m3u8"),"Public provider AES-256 zero-padded-key compatibility fixture");checks++;
        for(String unsafe:new String[]{"http://example.invalid/a","https://127.0.0.1/a","https://user:password@example.invalid/a","file:///a"}){
            try{NativePlayback.publicHttps(unsafe);throw new AssertionError("Invalid source URL accepted");}catch(java.io.IOException expected){}
        }checks++;
        Object category=decode("com.ellation.crunchyroll.model.categories.Category",NativeDiscovery.categories(false).getJSONArray("data").getJSONObject(0));
        check(call(category,"getTenantCategoryId").equals("action")&&call(call(category,"getLocalization"),"getTitle").equals("Action"),"Native category localization contract");checks++;
        JSONObject filters=NativeDiscovery.variables(android.net.Uri.parse("https://local/browse?categories=sci-fi,action&seasonal_tag=2026-fall&sort_by=alphabetical&q=Test"));
        check(filters.getJSONArray("genres").getString(0).equals("Sci-Fi")&&filters.getString("season").equals("FALL")&&filters.getInt("year")==2026&&filters.getJSONArray("sort").getString(0).equals("TITLE_ROMAJI"),"Discovery filters must preserve genre/year/sort semantics");checks++;
        check(NativeDiscovery.lowerBound(2,50,true)==101&&NativeDiscovery.lowerBound(3,7,false)==107,"Paging must use hasNextPage instead of inaccurate provider totals");checks++;
        try{NativeDiscovery.variables(android.net.Uri.parse("https://local/browse?categories=unknown"));throw new AssertionError("Unknown genres must fail");}catch(BackendBridge.HttpFailure expected){check(expected.status==400,"Invalid category status");checks++;}
        JSONObject enriched=new JSONObject(title.toString());enriched.getJSONArray("episodeList").getJSONObject(0).put("thumbnail",JSONObject.NULL).put("title",JSONObject.NULL);
        NativeMetadata.mergeEpisodes(enriched,new JSONObject().put("1",new JSONObject().put("image","https://example.invalid/episode1.jpg").put("title",new JSONObject().put("en","A real episode title")).put("overview","Episode overview")));
        JSONObject enrichedEpisode=NativeCatalog.episode(enriched,enriched.getJSONArray("episodeList").getJSONObject(0));
        check(enrichedEpisode.getString("title").equals("A real episode title")&&enrichedEpisode.getJSONObject("images").getJSONArray("thumbnail").getJSONArray(0).getJSONObject(0).getString("source").equals(NativeArtwork.wide("https://example.invalid/episode1.jpg"))&&enrichedEpisode.getJSONArray("versions").length()==2,"Episode metadata enrichment must retain source audio availability");checks++;
        JSONObject skip=NativePlayback.mapSkipEvents("ANI21E1",new JSONObject().put("intro",new JSONObject().put("start",31).put("end",111)).put("outro",new JSONObject().put("start",1376).put("end",1447)));
        Object skips=decode("com.ellation.crunchyroll.api.etp.playback.model.SkipEvents",skip);
        check(((Number)call(call(skips,"getIntro"),"getEndSeconds")).doubleValue()==111&&call(call(skips,"getCredits"),"getType").toString().equals("CREDITS"),"Native skip events must use provider timestamps and original enums");checks++;
        check(!NativePlayback.mapSkipEvents("ANI21E1",new JSONObject().put("intro",new JSONObject().put("start",10).put("end",10))).has("intro"),"Empty or invalid skip ranges must not produce controls");checks++;
        check(NativeAssets.avatar("ani-cover-21").endsWith("anilistId=21")&&NativeAssets.avatar("default.png").startsWith("https://ani.pm/")&&NativeAssets.avatar("https://user:password@example.invalid")==null,"Native asset URL mapping must only accept own catalog IDs");checks++;
        JSONObject nullable=new JSONObject().put("id",99).put("title",new JSONObject().put("english",JSONObject.NULL).put("romaji","Localized title")).put("description",JSONObject.NULL).put("coverImage",new JSONObject().put("large","https://example.invalid/cover.jpg"));
        check(NativeDiscovery.record(nullable).getString("title").equals("Localized title")&&NativeDiscovery.record(nullable).getString("synopsis").isEmpty(),"JSON null metadata must never render the literal null");checks++;
        JSONObject commentResponse=NativeCommunity.normalizeDates(new JSONObject().put("items",new org.json.JSONArray().put(new JSONObject().put("comment_id","123456").put("created","2026-10-05T12:26:58.718602+00:00").put("modified","2026-10-05T14:26:58.718602+02:00"))));
        Object datedComment=decodeComment(commentResponse.getJSONArray("items").getJSONObject(0));
        check(call(datedComment,"getCreated").equals(call(datedComment,"getModified")),"Cloud comment dates must parse in the original Gson adapter without a crash");checks++;
        check(Long.parseLong(call(datedComment,"getId").toString())==123456,"Original comment RecyclerView requires numeric stable IDs, not database UUIDs");checks++;
        check(NativeSubtitles.locale(new JSONObject().put("language","es").put("label","Spanish")).equals("es-ES"),"Spanish native locale mapping");checks++;
        check(NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Spanish (- Spanish(Latin America))")).equals("es-419"),"Latin American Spanish must not collapse into Spain");checks++;
        check(NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Portuguese (- Portuguese(Brazil))")).equals("pt-BR")&&NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Russian")).equals("ru-RU")&&NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Unknown")).isEmpty(),"Label fallback must preserve supported languages and reject unknown tracks");checks++;
        String ass=NativeSubtitles.toAss("WEBVTT\n\nintro\n00:01.250 --> 00:04.590 align:center\nHola, <b>mundo</b>!\nSecond line\n\n01:01:02.000 --> 01:01:03.000\nEspañol\n");
        check(ass.contains("Dialogue: 0,0:00:01.25,0:00:04.59,Default,,0,0,0,,Hola, mundo!\\NSecond line")&&ass.contains("1:01:02.00,1:01:03.00"),"WebVTT conversion must preserve cue timing, Unicode and line breaks");checks++;
        try{NativeSubtitles.toAss("<html>upstream error</html>");throw new AssertionError("HTML must not be accepted as subtitles");}catch(java.io.IOException expected){}checks++;
        check(!NativeSubtitles.toAss("WEBVTT\n\n00:01.000 --> 00:02.000\n{\\pos(1,2)}Text\n").contains("{\\pos"),"Subtitle data must not inject ASS overrides");checks++;
        check(NativePlayback.hardLocale(new JSONObject().put("hardsub_locale","es-419")).equals("es-419")&&NativePlayback.hardLocale(new JSONObject().put("type","sub")).isEmpty(),"Sub audio alone is not proof of burned-in subtitles");checks++;
        JSONObject spanishStreams=NativePlayback.streamJson("ANI154587E1","https://example.invalid/master.m3u8","sub",new org.json.JSONArray().put(new JSONObject().put("format","vtt").put("language","es").put("file","https://example.invalid/es.vtt")).put(new JSONObject().put("format","vtt").put("language","und").put("label","Spanish (Latin America)").put("file","https://example.invalid/latam.vtt")));
        Object spanishPlayer=NativePlayback.mapHls("ANI154587E1",decode("com.ellation.crunchyroll.api.cms.model.streams.Streams",spanishStreams),null,"");
        check(((java.util.List<?>)call(spanishPlayer,"f")).size()==2&&spanishStreams.getJSONObject("subtitles").getJSONObject("es-419").getString("url").startsWith("https://appassets.androidplatform.net/apkforge-subtitles/"),"Separate Spanish tracks must reach the original player through its local ASS renderer");checks++;
        JSONObject highRes=new JSONObject(nullable.toString()).put("coverImage",new JSONObject().put("large","https://example.invalid/small.jpg").put("extraLarge","https://example.invalid/hd.jpg"));
        check(NativeDiscovery.record(highRes).getString("poster").endsWith("/hd.jpg"),"Discovery must select actual extra-large source artwork");checks++;
        Class imageType=Class.forName("com.ellation.crunchyroll.ui.images.CloudflareImagesBuilder$ImageType");Object tallType=java.lang.Enum.valueOf(imageType,"TALL");
        Object builder=Class.forName("com.ellation.crunchyroll.ui.images.CloudflareImagesBuilder").getConstructor(String.class).newInstance("https://unavailable.invalid");
        check(builder.getClass().getMethod("build",String.class,imageType,java.util.List.class).invoke(builder,"ANI154587",tallType,java.util.Collections.emptyList()).equals(title.getString("poster")),"Original keyart URL builder must use replacement artwork instead of nonexistent original CDN IDs");checks++;
        check(NativeArtwork.url("ORIGINAL",tallType)==null,"Original non-adapter image IDs must retain their original mapping");checks++;
        JSONObject clover=new JSONObject(title.toString()).put("anilistId",97940);org.json.JSONArray allEpisodes=new org.json.JSONArray();for(int n=1;n<=170;n++)allEpisodes.put(new JSONObject(providerEpisode.toString()).put("number",n));clover.put("episodeList",allEpisodes);NativeSeasons.apply(clover,null);cached.put(97940,clover);
        JSONObject seasons=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/series/ANI97940/seasons"));
        check(seasons.getJSONArray("data").length()==4&&seasons.getJSONArray("data").getJSONObject(3).getInt("number_of_episodes")==16,"Black Clover release groups must cover 170 real provider episodes");checks++;
        JSONObject seasonTwo=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/seasons/ANI97940S2/episodes"));
        check(seasonTwo.getJSONArray("data").length()==51&&seasonTwo.getJSONArray("data").getJSONObject(0).getString("id").equals("ANI97940E52")&&seasonTwo.getJSONArray("data").getJSONObject(0).getJSONArray("versions").getJSONObject(1).getString("season_guid").equals("ANI97940S2"),"Season selection must preserve absolute playback and audio version group IDs");checks++;
        check(NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/discover/up_next/ANI97940E51")).getJSONArray("data").getJSONObject(0).getJSONObject("panel").getJSONObject("episode_metadata").getString("season_id").equals("ANI97940S2"),"Next episode must cross a season boundary without returning Home");checks++;
        check(NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Vietnamese")).equals("vi-VN")&&NativeSubtitles.locale(new JSONObject().put("language","zh-Hant")).equals("zh-TW")&&NativeSubtitles.locale(new JSONObject().put("language","und").put("label","Polish")).equals("pl-PL"),"Additional provider languages must retain usable native locale tags");checks++;
        JSONObject newSummary=new JSONObject(title.toString());newSummary.remove("episodeList");newSummary.put("poster","https://example.invalid/refreshed-hd.jpg");BackendBridge.cache(new org.json.JSONArray().put(newSummary));
        check(BackendBridge.cachedTitle(154587).has("episodeList")&&BackendBridge.cachedTitle(154587).getString("poster").endsWith("refreshed-hd.jpg"),"Artwork refresh must update already-opened series without discarding episodes");checks++;
        for(int n=0;n<10;n++)cached.put(500000+n,new JSONObject(clover.toString()).put("anilistId",500000+n));BackendBridge.trimDetails();
        int detailed=0;for(JSONObject cachedRecord:cached.values())if(cachedRecord.has("episodeList"))detailed++;
        check(detailed<=8&&cached.get(500009).has("episodeList")&&!cached.get(97940).has("episodeList")&&BackendBridge.panel(cached.get(97940)).getJSONObject("series_metadata").getInt("season_count")==4,"Memory eviction must retain recent details and old title/season navigation metadata");checks++;
        java.lang.reflect.Field metadataCache=NativeMetadata.class.getDeclaredField("CACHE");metadataCache.setAccessible(true);java.util.Map memory=(java.util.Map)metadataCache.get(null);
        Class entry=Class.forName("dev.apkforge.bridge.NativeMetadata$Entry");java.lang.reflect.Constructor createEntry=entry.getDeclaredConstructor(JSONObject.class,long.class);createEntry.setAccessible(true);char[] padding=new char[524288];java.util.Arrays.fill(padding,'x');
        for(int n=0;n<8;n++)memory.put("memory-fixture-"+n,createEntry.newInstance(new JSONObject().put("payload",new String(padding)),60000L));NativeMetadata.trimCache();
        long chars=0;java.lang.reflect.Field dataField=entry.getDeclaredField("data");dataField.setAccessible(true);for(Object value:memory.values())chars+=((String)dataField.get(value)).length();
        check(chars<=3*1024*1024&&memory.size()<8,"A few large metadata responses must respect memory budgets before the entry-count limit");memory.clear();checks++;
        check(!BackendBridge.signedIn(new Object()),"Missing app/session context must not grant guest access");checks++;
        int[] panorama=NativeArtwork.cropBounds(2300,450),portrait=NativeArtwork.cropBounds(600,900);
        check(panorama[2]==800&&panorama[3]==450&&panorama[0]==750,"Panorama must be cropped to 16:9, not flattened");checks++;
        check(portrait[2]==600&&portrait[3]==337&&portrait[1]>0,"Portrait fallback preserves proportions with a bounded crop");checks++;
        android.graphics.Bitmap bitmap=android.graphics.Bitmap.createBitmap(2300,450,android.graphics.Bitmap.Config.RGB_565);java.io.ByteArrayOutputStream bitmapBytes=new java.io.ByteArrayOutputStream();bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,bitmapBytes);bitmap.recycle();
        byte[] cropped=NativeArtwork.crop(bitmapBytes.toByteArray());android.graphics.BitmapFactory.Options dimensions=new android.graphics.BitmapFactory.Options();dimensions.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(cropped,0,cropped.length,dimensions);
        check(dimensions.outWidth==800&&dimensions.outHeight==450,"Actual decoded artwork keeps intended dimensions without upscaling");checks++;
        Object sizeModel=Class.forName("com.ellation.crunchyroll.ui.images.BestImageSizeModelUrlImpl").getConstructor(String.class).newInstance(NativeArtwork.wide("https://example.invalid/art.jpg"));
        Object load=NativeArtwork.load(sizeModel,640,360);check(load!=null&&call(load.getClass().getField("c").get(load),"a").equals(java.io.InputStream.class),"Registered wide images use the original Glide data-fetcher contract");checks++;
        JSONObject source2=new JSONObject(title.toString()).put("anilistId",154588).put("poster","https://example.invalid/latest.jpg");
        JSONObject joined=NativeFranchises.merge(java.util.Arrays.asList(title,source2));
        check(joined.getJSONArray("episodeList").length()==4&&NativeSeasons.numbers(joined).size()==2&&joined.getString("poster").endsWith("latest.jpg"),"Verified seasons keep all episodes and latest artwork");checks++;
        JSONObject joinedEpisode=NativeCatalog.episode(joined,joined.getJSONArray("episodeList").getJSONObject(2));
        check(joinedEpisode.getString("id").equals("ANI154588E1")&&joinedEpisode.getString("series_id").equals("ANI154587")&&joinedEpisode.getString("season_id").equals("ANI154587S2"),"Season 2 E1 must resolve its source ID, while navigation uses the common series");checks++;
        cached.put(154587,joined);cached.put(154588,joined);
        check(NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/discover/up_next/ANI154587E2")).getJSONArray("data").getJSONObject(0).getJSONObject("panel").getString("id").equals("ANI154588E1"),"Next must cross different provider series IDs at a season boundary");checks++;
        check(NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/discover/up_next/ANI154588E1D")).getJSONArray("data").getJSONObject(0).getJSONObject("panel").getString("id").equals("ANI154588E2D"),"Next must retain source season and requested dubbed audio");checks++;
        JSONObject firstSeason=new JSONObject().put("anilistId",27000).put("format","TV").put("title","Grouped title").put("status","FINISHED").put("poster","https://example.invalid/first.jpg").put("episodes",new JSONObject().put("total",12)).put("relations",new org.json.JSONArray().put(new JSONObject().put("relationType","SEQUEL").put("node",new JSONObject().put("id",27001).put("format","TV").put("status","FINISHED"))));
        JSONObject secondSeason=new JSONObject(firstSeason.toString()).put("anilistId",27001).put("poster","https://example.invalid/second.jpg").put("relations",new org.json.JSONArray().put(new JSONObject().put("relationType","PREQUEL").put("node",new JSONObject().put("id",27000).put("format","TV").put("status","FINISHED"))));
        org.json.JSONArray collapsed=NativeFranchises.collapse(new org.json.JSONArray().put(secondSeason).put(firstSeason));
        check(collapsed.length()==1&&collapsed.getJSONObject(0).getInt("anilistId")==27000&&collapsed.getJSONObject(0).getJSONObject("episodes").getInt("total")==24,"Search merges actual sequels regardless of result order");checks++;
        JSONObject ova=new JSONObject(firstSeason.toString()).put("format","OVA");check(NativeFranchises.links(ova,"SEQUEL").isEmpty(),"OVAs and movies must not become TV seasons by name guessing");checks++;
        org.json.JSONArray benefits=NativeDownloads.benefits().getJSONArray("items");java.util.List<Object> benefitModels=new java.util.ArrayList<>();for(int i=0;i<benefits.length();i++)benefitModels.add(decode("com.ellation.crunchyroll.api.etp.subscription.model.Benefit",benefits.getJSONObject(i)));
        Class<?> benefitKt=Class.forName("com.ellation.crunchyroll.api.etp.subscription.model.BenefitKt");check((Boolean)benefitKt.getMethod("isAtLeastMegaFanUser",java.util.List.class).invoke(null,benefitModels)&&(Boolean)benefitKt.getMethod("hasOfflineViewingBenefit",java.util.List.class).invoke(null,benefitModels),"Replacement accounts expose full local capabilities without purchasing an official subscription");checks++;
        check(NativeDownloads.variant("https://example.invalid/master.m3u8","#EXTM3U\n#EXT-X-STREAM-INF:RESOLUTION=1280x720\n720.m3u8\n#EXT-X-STREAM-INF:RESOLUTION=640x360\n360.m3u8\n",480).endsWith("360.m3u8"),"Offline quality uses the actual requested HLS variant");checks++;
        NativeDownloads.validate("#EXTM3U\n#EXTINF:10,\na.ts\n#EXT-X-ENDLIST\n");checks++;
        for(String invalid:new String[]{"#EXTM3U\n#EXTINF:10,\na.ts","#EXTM3U\n#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT=\"com.apple.streamingkeydelivery\"\n#EXT-X-ENDLIST","#EXTM3U\n#EXT-X-KEY:METHOD=AES-128-INVALID\n#EXT-X-ENDLIST"}){try{NativeDownloads.validate(invalid);throw new AssertionError("Unsupported offline manifest accepted");}catch(java.io.IOException expected){}}checks++;
        Object download=decode("com.ellation.crunchyroll.api.etp.download.model.DownloadResponse",NativeDownloads.response("https://example.invalid/360.m3u8",new JSONObject().put("es-ES",new JSONObject().put("locale","es-ES").put("format","ass").put("url","https://example.invalid/sub.ass").put("localFilePath","/data/user/0/test/offline.ass"))));
        check(call(download,"getManifestUrl").equals("https://example.invalid/360.m3u8")&&call(download,"getVideoToken").equals("")&&call(((java.util.Map<?,?>)call(download,"getSubtitles")).get("es-ES"),"getLocalFilePath").equals("/data/user/0/test/offline.ass"),"Original download model retains media URI and local subtitle file");checks++;
        Class<?> managerClass=Class.forName("com.ellation.crunchyroll.downloading.exoplayer.ExoPlayerLocalVideosManagerImpl"),streamClass=Class.forName("com.ellation.crunchyroll.api.cms.model.streams.Stream");
        Class.forName(managerClass.getName()+"$h").getConstructor(String.class,streamClass,managerClass);Class.forName(managerClass.getName()+"$h").getMethod("invoke",Object.class);
        Class.forName(managerClass.getName()+"$i").getConstructor(managerClass,String.class);Class.forName(managerClass.getName()+"$i").getMethod("invoke",Object.class);checks++;
        check(Class.forName("b6.i").getField("b").getType().equals(Class.forName("b6.u"))&&Class.forName("b6.u").getMethod("c",String.class).getReturnType().equals(Class.forName("b6.c"))&&Class.forName("b6.c").getField("b").getType().equals(int.class),"Original offline index exposes the expected completion state contract");checks++;
        check(NativeSubtitles.toAss("WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHola\n").contains("Style: Default,Arial,40,&H00FFFFFF,&H00FFFFFF,&H00000000,&H80000000,-1"),"Separate tracks match bold white text with black outline");checks++;
        check(NativeMetadata.retryMillis("120",System.currentTimeMillis())==120000&&NativeMetadata.retryMillis("9223372036854775807",0)==900000&&NativeMetadata.retryMillis("invalid",0)==60000,"Provider Retry-After is bounded without integer overflow");checks++;
        java.util.concurrent.atomic.AtomicInteger fetches=new java.util.concurrent.atomic.AtomicInteger();java.util.concurrent.CountDownLatch fetching=new java.util.concurrent.CountDownLatch(1),release=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.ExecutorService consumers=java.util.concurrent.Executors.newFixedThreadPool(2);
        try{java.util.concurrent.Future<JSONObject> first=consumers.submit(()->NativeMetadata.cachedRequest("https://single.example.invalid/api","single-flight",120000,()->{fetches.incrementAndGet();fetching.countDown();if(!release.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Fixture timed out");return new JSONObject().put("generation",1);}));check(fetching.await(2,java.util.concurrent.TimeUnit.SECONDS),"Fixture first fetch not started");java.util.concurrent.Future<JSONObject> second=consumers.submit(()->NativeMetadata.cachedRequest("https://single.example.invalid/api","single-flight",120000,()->{fetches.incrementAndGet();return new JSONObject().put("generation",2);}));release.countDown();check(first.get(2,java.util.concurrent.TimeUnit.SECONDS).getInt("generation")==1&&second.get(2,java.util.concurrent.TimeUnit.SECONDS).getInt("generation")==1&&fetches.get()==1,"Concurrent catalog requests must share one successful fetch");checks++;}finally{release.countDown();consumers.shutdownNow();}
        @SuppressWarnings("unchecked") java.util.Map<String,Object> metadata=(java.util.Map<String,Object>)metadataCache.get(null);
        Class<?> cacheEntry=Class.forName("dev.apkforge.bridge.NativeMetadata$Entry");java.lang.reflect.Constructor<?> cacheConstructor=cacheEntry.getDeclaredConstructor(JSONObject.class,long.class);cacheConstructor.setAccessible(true);
        metadata.put("expired-rate",cacheConstructor.newInstance(new JSONObject().put("catalog","last-good"),-1L));
        check(NativeMetadata.cachedRequest("https://rate.example.invalid/api","expired-rate",120000,()->{throw new NativeMetadata.ProviderFailure(429,60000);}).getString("catalog").equals("last-good"),"An expired valid catalog must survive a provider rate limit");checks++;
        try{NativeMetadata.cachedRequest("https://rate.example.invalid/api","uncached-rate",120000,()->{throw new AssertionError("Cooldown must prevent another network request");});throw new AssertionError("Uncached request must report real unavailability");}catch(NativeMetadata.ProviderFailure expected){check(expected.status==429&&expected.retryMillis>0,"Cooldown retry information missing");}checks++;
        metadata.put("removed-title",cacheConstructor.newInstance(new JSONObject().put("catalog","removed"),-1L));try{NativeMetadata.cachedRequest("https://removed.example.invalid/api","removed-title",120000,()->{throw new NativeMetadata.ProviderFailure(404,0);});throw new AssertionError("Removed title must not be masked by stale data");}catch(NativeMetadata.ProviderFailure expected){check(expected.status==404,"Wrong non-temporary error");}checks++;
        java.io.File publicFolder=java.nio.file.Files.createTempDirectory(java.nio.file.Paths.get("/data/local/tmp/apkforge-model-contracts"),"public-cache-").toFile();
        try{NativePublicStore.write(publicFolder,"public-fixture",new JSONObject().put("fresh","catalog"));JSONObject disk=NativePublicStore.read(publicFolder,"public-fixture");check(disk!=null&&disk.getJSONObject("value").getString("fresh").equals("catalog")&&publicFolder.listFiles()[0].getName().matches("[a-f0-9]{64}\\.json"),"Public catalog cache survives a memory reset with opaque filenames");checks++;
            try(java.io.FileOutputStream bad=new java.io.FileOutputStream(publicFolder.listFiles()[0])){bad.write("broken-json".getBytes(java.nio.charset.StandardCharsets.UTF_8));}check(NativePublicStore.read(publicFolder,"public-fixture")==null,"Corrupt disk cache must be ignored safely");checks++;
        }finally{for(java.io.File own:publicFolder.listFiles())own.delete();publicFolder.delete();}
        check(!NativeHomeFeed.acceptRefresh(new org.json.JSONArray().put(1).put(2).put(3).put(4),new org.json.JSONArray().put(1))&&NativeHomeFeed.acceptRefresh(null,new org.json.JSONArray().put(1)),"A partial outage must not replace a richer active Home snapshot");checks++;
        java.lang.reflect.Field relationships=NativeFranchises.class.getDeclaredField("RECORDS");relationships.setAccessible(true);((java.util.Map<?,?>)relationships.get(null)).remove(27000);
        org.json.JSONArray stableCards=new org.json.JSONArray();java.util.Set<Integer> seenSearch=new java.util.HashSet<>();NativeDiscovery.appendStable(stableCards,new org.json.JSONArray().put(secondSeason),seenSearch);int firstId=stableCards.getJSONObject(0).getInt("anilistId");NativeDiscovery.appendStable(stableCards,new org.json.JSONArray().put(firstSeason).put(new JSONObject().put("anilistId",29000).put("title","New unrelated result")),seenSearch);
        check(firstId==27001&&stableCards.length()==2&&stableCards.getJSONObject(0).getInt("anilistId")==firstId&&stableCards.getJSONObject(1).getInt("anilistId")==29000,"A prequel on a later search page must not shift or duplicate earlier results");checks++;
        check(NativeSubtitles.toAss("1\n00:00:01,250 --> 00:00:04,590\nEspañol, mañana\n").contains("Dialogue: 0,0:00:01.25,0:00:04.59,Default,,0,0,0,,Español, mañana"),"Actual SRT Unicode and millisecond timing must reach the original renderer");checks++;
        check(NativeSubtitles.toAss("[Script Info]\nScriptType: v4.00+\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.25,0:00:04.59,Original,,0,0,0,,{\\c&HFF0000&}Hola, mundo\\NSecond line\n").contains("Default,,0,0,0,,Hola, mundo\\NSecond line"),"ASS sources keep real text/timing and use requested readable styling");checks++;
        JSONObject additionalTracks=NativePlayback.streamJson("ANI154587E1","https://example.invalid/master.m3u8","sub",new org.json.JSONArray().put(new JSONObject().put("language","es").put("file","https://example.invalid/es.srt")).put(new JSONObject().put("language","fr").put("file","https://example.invalid/fr.ass")));
        check(additionalTracks.getJSONObject("subtitles").has("es-ES")&&additionalTracks.getJSONObject("subtitles").has("fr-FR"),"Real SRT/ASS tracks must not be discarded before native language selection");checks++;
        java.lang.reflect.Field tracksField=NativeSubtitles.class.getDeclaredField("TRACKS");tracksField.setAccessible(true);@SuppressWarnings("unchecked") java.util.Map<String,Object> registered=(java.util.Map<String,Object>)tracksField.get(null);for(int i=0;i<540;i++)NativeSubtitles.register("https://example.invalid/track-"+i+".vtt");String recentTrack=NativeSubtitles.register("https://example.invalid/track-539.vtt");check(registered.size()==512&&recentTrack.equals(NativeSubtitles.register("https://example.invalid/track-539.vtt")),"Track registry covers the bounded stream cache without growing indefinitely");checks++;
        Object keptTrack=registered.get(recentTrack),oldTrack=registered.values().iterator().next();java.lang.reflect.Field assField=keptTrack.getClass().getDeclaredField("ass");assField.setAccessible(true);assField.set(oldTrack,new String(new char[1500000]));assField.set(keptTrack,new String(new char[1500000]));java.lang.reflect.Method trimTracks=NativeSubtitles.class.getDeclaredMethod("trim",keptTrack.getClass());trimTracks.setAccessible(true);trimTracks.invoke(null,keptTrack);check(assField.get(oldTrack)==null&&assField.get(keptTrack)!=null,"Subtitle memory eviction must retain the active track and release old cue buffers");checks++;
        cached.put(154587,joined);cached.put(154588,joined);JSONObject watched=new JSONObject();NativeHistory.save(watched,new JSONObject().put("batch",new JSONObject().put("ANI154587E1",new JSONObject().put("playhead",80).put("date_watched","2026-01-01T00:00:00Z")).put("ANI154588E1D",new JSONObject().put("playhead",120).put("date_watched","2026-01-02T00:00:00Z"))));check(watched.length()==2&&watched.getJSONObject("ANI154588E1D").has("_episode"),"Batch progress must save real episode metadata for later history rendering");checks++;
        JSONObject continued=NativeHistory.rows(watched,android.net.Uri.parse("https://local/content/v2/discover/me/history?n=25"));Object continueModel=decode("com.ellation.crunchyroll.api.model.ContinueWatchingPanel",continued.getJSONArray("data").getJSONObject(0));check(continued.getJSONArray("data").length()==1&&((Number)call(continueModel,"getPlayhead")).longValue()==120&&call(call(continueModel,"getPanel"),"getId").equals("ANI154588E1D"),"Continue watching must select the latest episode in a shared season group");checks++;
        JSONObject history=NativeHistory.rows(watched,android.net.Uri.parse("https://local/content/v2/me/watch-history?page_size=1"));Object historyModel=decode("com.ellation.crunchyroll.api.etp.content.model.WatchHistoryPanel",history.getJSONArray("data").getJSONObject(0));check(((Number)call(historyModel,"getPlayhead")).longValue()==120&&history.getJSONObject("meta").has("next_page"),"Native history exposes real progress and a next page");checks++;
        String beforeInvalid=watched.toString();try{NativeHistory.save(watched,new JSONObject().put("batch",new JSONObject().put("ANI154587E2",new JSONObject().put("playhead",4)).put("INVALID",new JSONObject())));throw new AssertionError("Invalid batch accepted");}catch(BackendBridge.HttpFailure expected){check(watched.toString().equals(beforeInvalid),"Invalid batch must not partially mutate progress");}checks++;
        check(NativeHistory.rows(new JSONObject(),android.net.Uri.parse("https://local/content/v2/me/watch-history")).getJSONArray("data").length()==0,"History must use only the supplied authenticated profile state");checks++;
        NativeHistory.delete(watched,"ANI154588E1D");check(watched.length()==1&&!watched.has("ANI154588E1D"),"Native history delete clears only the selected progress record");checks++;
        Object continueRow=decode("com.ellation.crunchyroll.api.model.HomeFeedItemRaw",NativeHomeFeed.continueRow());check((Boolean)call(continueRow,"isValid")&&call(continueRow,"getResourceType").toString().equals("CONTINUE_WATCHING")&&call(continueRow,"getResponseType").toString().equals("HISTORY"),"Home must load real progress through its original continue-watching handler");checks++;
        check(NativeDownloads.requiredSubtitle(new JSONObject().put("en-US",1).put("es-419",1),"es-ES").equals("es-419")&&NativeDownloads.requiredSubtitle(new JSONObject().put("en-US",1).put("fr-FR",1),"de-DE").equals("en-US"),"Offline preparation prioritizes the requested language and an available fallback");checks++;
        check(NativeSubtitles.toAss("WEBVTT\n\n00:99:01.000 --> 00:99:04.000\nInvalid cue\n\n00:00:01.000 --> 00:00:04.000\nValid cue\n").contains("Valid cue")&&NativeSubtitles.supported("application/x-subrip","/caption")&&NativeSubtitles.supported("text/x-ass","/caption"),"One malformed cue must not suppress valid dialogue; explicit subtitle MIME types are supported");checks++;
        check(NativeDiscovery.feedVariables("movies").getString("format").equals("MOVIE")&&NativeDiscovery.feedVariables("action").getJSONArray("genres").getString(0).equals("Action")&&NativeDiscovery.feedVariables("trending").getJSONArray("sort").getString(0).equals("TRENDING_DESC"),"Hybrid Home fallback must retain movie, genre and actual trending filters");checks++;
        android.net.Uri moviePage=NativeDiscovery.collectionUri("movies",50,25);check(moviePage.getQueryParameter("start").equals("50")&&moviePage.getQueryParameter("n").equals("25")&&NativeDiscovery.variables(moviePage).getString("format").equals("MOVIE")&&NativeDiscovery.variables(NativeDiscovery.collectionUri("action",25,25)).getJSONArray("genres").getString(0).equals("Action"),"View All fallback must preserve collection filters and native page offsets");checks++;
        JSONObject lostAvailability=BackendBridge.unavailableDetail(new JSONObject().put("anilistId",154599).put("title","Known metadata").put("episodes",new JSONObject().put("total",12)).put("poster","https://example.invalid/hd.jpg"));Object unavailablePanel=decode("com.ellation.crunchyroll.model.Panel",BackendBridge.panel(lostAvailability));check(call(unavailablePanel,"getId").equals("ANI154599")&&lostAvailability.getJSONArray("episodeList").length()==0&&lostAvailability.optBoolean("_availabilityUnknown")&&lostAvailability.getString("synopsis").contains("temporarily unavailable"),"Missing availability must retain valid native details without inventing episodes or audio");checks++;
        String stableHistory=watched.toString();try{NativeHistory.save(watched,new JSONObject().put("batch",new JSONObject().put("ANI154587E1",new JSONObject().put("playhead",9)).put("ANI999999999999999999999E1",new JSONObject().put("playhead",9))));throw new AssertionError("Overflowing history asset accepted");}catch(BackendBridge.HttpFailure expected){check(watched.toString().equals(stableHistory),"Overflowing progress must not partially update a profile");}checks++;
        check(NativeDiscovery.variables(NativeDiscovery.relatedUri(new JSONObject().put("genres",new org.json.JSONArray().put("Unknown category").put("Fantasy")))).getJSONArray("genres").getString(0).equals("Fantasy")&&!NativeDiscovery.variables(NativeDiscovery.relatedUri(new JSONObject())).has("genres"),"Related metadata fallback must retain a real supported genre without rejecting unmapped genres");checks++;
        check(CloudSession.confirmedUser(new JSONObject().put("user",new JSONObject().put("email_confirmed_at","2026-01-01T00:00:00Z")))&&!CloudSession.confirmedUser(new JSONObject().put("user",new JSONObject().put("email_confirmed_at",JSONObject.NULL)))&&!CloudSession.confirmedUser(null),"Native confirmation state must derive from actual Supabase confirmation, never just an authenticated-looking user");checks++;
        String emptyNextPath="/content/v2/discover/up_next/ANI154599";int emptyNextStatus=BackendBridge.successStatus(emptyNextPath,BackendBridge.envelope(new org.json.JSONArray()));
        check(emptyNextStatus==204&&BackendBridge.successStatus(emptyNextPath,BackendBridge.envelope(new org.json.JSONArray().put(new JSONObject())))==200&&BackendBridge.successStatus("/content/v2/browse",BackendBridge.envelope(new org.json.JSONArray()))==200,"Empty Up Next must use the original No Content contract without changing empty catalog responses");checks++;
        Class<?> requestBuilder=Class.forName("me0.a0$a"),requestType=Class.forName("me0.a0"),rawResponse=Class.forName("me0.e0"),retrofitResponse=Class.forName("df0.c0"),serviceType=Class.forName("com.ellation.crunchyroll.api.etp.content.EtpContentService"),resourceType=Class.forName("p80.u"),inputType=Class.forName("g70.j"),interactorType=Class.forName("g70.f");
        Object rb=requestBuilder.getConstructor().newInstance();requestBuilder.getMethod("g",String.class).invoke(rb,"https://local"+emptyNextPath);Object rr=BackendBridge.response(ModelContractProbe.class.getClassLoader(),requestBuilder.getMethod("b").invoke(rb),emptyNextStatus,"");Object wrapped=retrofitResponse.getConstructor(rawResponse,Object.class).newInstance(rr,null);
        Object service=java.lang.reflect.Proxy.newProxyInstance(serviceType.getClassLoader(),new Class<?>[]{serviceType},(proxy,method,arguments)->{if(method.getName().equals("getUpNextEpisode"))return wrapped;throw new AssertionError("Unexpected content call "+method.getName());});
        @SuppressWarnings({"unchecked","rawtypes"}) Object seriesType=Enum.valueOf((Class)resourceType,"SERIES");Object input=inputType.getConstructor(resourceType,String.class,String.class).newInstance(seriesType,"ANI154599",null),originalInteractor=interactorType.getConstructor(inputType,serviceType,Class.forName("dx.a")).newInstance(input,service,null);
        try{interactorType.getMethod("l",Class.forName("zc0.d")).invoke(originalInteractor,new Object[]{null});throw new AssertionError("Empty Up Next unexpectedly produced a playable asset");}catch(java.lang.reflect.InvocationTargetException expected){check(expected.getCause().getClass().getName().equals("nr.b"),"Original interactor must return its handled no-content error, never a main-thread empty-list crash: "+expected.getCause().getClass().getName());}checks++;
        JSONObject secondarySummary=new JSONObject(title.toString()).put("malId",52991);
        JSONObject secondaryRecord=new JSONObject().put("id","watch/anikoto/154587/sub/anikoto-1").put("number",1).put("audio","sub").put("hasSub",true).put("hasDub",true).put("duration",1440).put("title","Actual episode").put("image","https://example.invalid/episode.jpg");
        JSONObject secondaryPayload=new JSONObject().put("meta",new JSONObject().put("malId",52991)).put("episodes",new JSONObject().put("sub",new org.json.JSONArray().put(secondaryRecord).put(secondaryRecord)).put("dub",new org.json.JSONArray()));
        JSONObject mappedSecondary=NativeEpisodes.map(154587,secondarySummary,secondaryPayload);Object mappedEpisode=decode("com.ellation.crunchyroll.model.Episode",NativeCatalog.episode(mappedSecondary,mappedSecondary.getJSONArray("episodeList").getJSONObject(0)));
        check(call(mappedEpisode,"getId").equals("ANI154587E1")&&mappedSecondary.getJSONObject("episodes").getInt("sub")==1&&mappedSecondary.getJSONObject("episodes").getInt("dub")==0&&((java.util.List<?>)call(mappedEpisode,"getVersions")).size()==1,"Secondary episodes must deduplicate actual listed audio; hasDub alone does not invent a dub");checks++;
        JSONObject dubRecord=new JSONObject(secondaryRecord.toString()).put("id","watch/anikoto/154587/dub/anikoto-3").put("number",3).put("audio","dub");secondaryPayload.getJSONObject("episodes").getJSONArray("dub").put(dubRecord);
        mappedSecondary=NativeEpisodes.map(154587,secondarySummary,secondaryPayload);check(mappedSecondary.getJSONArray("episodeList").length()==2&&mappedSecondary.getJSONArray("episodeList").getJSONObject(1).getInt("number")==3&&NativeCatalog.episode(mappedSecondary,mappedSecondary.getJSONArray("episodeList").getJSONObject(1)).getString("id").equals("ANI154587E3D"),"Sparse secondary numbering and dub-only assets must stay exact");checks++;
        try{NativeEpisodes.map(154587,secondarySummary,new JSONObject(secondaryPayload.toString()).put("meta",new JSONObject().put("malId",JSONObject.NULL)));throw new AssertionError("Guessed no-MAL availability accepted");}catch(java.io.IOException expected){checks++;}
        try{NativeEpisodes.map(154587,secondarySummary,new JSONObject(secondaryPayload.toString()).put("meta",new JSONObject().put("malId",20)));throw new AssertionError("Wrong MAL identity accepted");}catch(java.io.IOException expected){checks++;}
        secondaryRecord.put("id","watch/anikoto/20/sub/anikoto-1");try{NativeEpisodes.map(154587,secondarySummary,secondaryPayload);throw new AssertionError("Wrong source identity accepted");}catch(java.io.IOException expected){checks++;}secondaryRecord.put("id","watch/anikoto/154587/sub/anikoto-1");
        secondaryRecord.put("number",1.5);try{NativeEpisodes.map(154587,secondarySummary,secondaryPayload);throw new AssertionError("Fractional episode accepted");}catch(java.io.IOException expected){checks++;}secondaryRecord.put("number",1);
        java.util.concurrent.atomic.AtomicLong watchClock=new java.util.concurrent.atomic.AtomicLong(1000);NativeWatchCache watchCache=new NativeWatchCache(watchClock::get);java.util.concurrent.atomic.AtomicInteger watchRequests=new java.util.concurrent.atomic.AtomicInteger();java.util.concurrent.ExecutorService watchWorkers=java.util.concurrent.Executors.newFixedThreadPool(4);java.util.List<java.util.concurrent.Future<JSONObject>> watchTasks=new java.util.ArrayList<>();java.util.concurrent.CountDownLatch watchGate=new java.util.concurrent.CountDownLatch(1);
        try{for(int w=0;w<4;w++)watchTasks.add(watchWorkers.submit(()->{watchGate.await();return watchCache.get("ANI20E1",()->{watchRequests.incrementAndGet();Thread.sleep(40);return new JSONObject().put("streams",new org.json.JSONArray()).put("intro",new JSONObject().put("start",0).put("end",89));});}));watchGate.countDown();for(java.util.concurrent.Future<JSONObject> task:watchTasks)task.get(3,java.util.concurrent.TimeUnit.SECONDS).remove("intro");check(watchRequests.get()==1&&watchCache.get("ANI20E1",()->{throw new AssertionError("Duplicate provider call");}).has("intro"),"Concurrent stream and skip requests must share one fetch and independent JSON copies");checks++;}finally{watchWorkers.shutdownNow();}
        watchClock.addAndGet(45001);watchCache.get("ANI20E1",()->{watchRequests.incrementAndGet();return new JSONObject();});check(watchRequests.get()==2,"Expired watch URLs must refresh without stale fallback");checks++;
        java.util.concurrent.atomic.AtomicInteger failedWatches=new java.util.concurrent.atomic.AtomicInteger();NativeWatchCache.Fetch failingWatch=()->{failedWatches.incrementAndGet();throw new java.io.IOException("provider unavailable");};for(int w=0;w<2;w++)try{watchCache.get("ANI20E2",failingWatch);throw new AssertionError("Failed source became successful");}catch(java.io.IOException expected){}watchClock.addAndGet(5001);watchCache.get("ANI20E2",()->{failedWatches.incrementAndGet();return new JSONObject();});check(failedWatches.get()==2,"Short provider failure cooldown must suppress duplicates then allow recovery");checks++;
        for(int w=0;w<20;w++)watchCache.get("ANI20E"+(w+10),()->new JSONObject());java.lang.reflect.Field watchValues=NativeWatchCache.class.getDeclaredField("values");watchValues.setAccessible(true);check(((java.util.Map<?,?>)watchValues.get(watchCache)).size()<=16,"Media bundle cache must remain memory bounded");checks++;
        check(NativePlayback.directSource(new JSONObject().put("type","hls").put("referer",NativePlayback.REFERER).put("url","https://example.invalid/master.m3u8"))&&!NativePlayback.directSource(new JSONObject().put("type","hls").put("referer","https://different.invalid/").put("url","https://example.invalid/master.m3u8")),"Direct HLS must use the retained provider header contract, never mismatched headers");checks++;
        java.util.concurrent.atomic.AtomicInteger artworkDisconnects=new java.util.concurrent.atomic.AtomicInteger();java.net.HttpURLConnection artworkConnection=new java.net.HttpURLConnection(new java.net.URL("https://example.invalid/image.jpg")){public void connect(){}public void disconnect(){artworkDisconnects.incrementAndGet();}public boolean usingProxy(){return false;}};
        NativeArtwork.Request artworkRequest=new NativeArtwork.Request();artworkRequest.attach(artworkConnection);artworkRequest.cancel();check(artworkRequest.canceled()&&artworkDisconnects.get()==1,"Scrolling away must disconnect a canceled image fetch rather than occupy Glide workers");checks++;
        try{artworkRequest.attach(artworkConnection);throw new AssertionError("Canceled image restarted");}catch(java.io.IOException expected){check(artworkDisconnects.get()==2,"A cancel-before-connect race must disconnect the unused connection");}try{artworkRequest.check();throw new AssertionError("Canceled image reached bitmap decode");}catch(java.io.IOException expected){}checks++;
        JSONObject requestedSeason=new JSONObject().put("anilistId",100).put("episodeList",new org.json.JSONArray().put(new JSONObject().put("number",1)));java.util.concurrent.CountDownLatch seasonGate=new java.util.concurrent.CountDownLatch(3);
        java.util.List<JSONObject> parallelSeasons=NativeFranchises.relatedSources(java.util.Arrays.asList(100,101,102,103),100,requestedSeason,n->{seasonGate.countDown();if(!seasonGate.await(2,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Season requests serialized");return new JSONObject().put("anilistId",n).put("episodeList",new org.json.JSONArray().put(new JSONObject().put("number",1)));},3000);
        check(parallelSeasons.size()==4&&parallelSeasons.get(0).getInt("anilistId")==100&&parallelSeasons.get(3).getInt("anilistId")==103,"Related seasons must load concurrently while preserving original source ordering");checks++;
        java.util.List<JSONObject> partialSeasons=NativeFranchises.relatedSources(java.util.Arrays.asList(100,101,102),100,requestedSeason,n->{if(n==101)throw new java.io.IOException("season unavailable");return new JSONObject().put("anilistId",999).put("episodeList",new org.json.JSONArray().put(new JSONObject()));},1000);check(partialSeasons.size()==1&&partialSeasons.get(0)==requestedSeason,"Unavailable or mismatched related seasons must retain the requested real episodes");checks++;
        long seasonStarted=System.nanoTime();java.util.List<JSONObject> timedSeasons=NativeFranchises.relatedSources(java.util.Arrays.asList(100,101),100,requestedSeason,n->{Thread.sleep(1000);return requestedSeason;},30);check(timedSeasons.size()==1&&java.util.concurrent.TimeUnit.NANOSECONDS.toMillis(System.nanoTime()-seasonStarted)<900,"A slow related season must not hold the requested title past the shared deadline");checks++;
        java.util.concurrent.atomic.AtomicInteger unknownSeasonFetches=new java.util.concurrent.atomic.AtomicInteger();check(NativeFranchises.relatedSources(java.util.Arrays.asList(100,101),100,new JSONObject().put("anilistId",100).put("episodeList",new org.json.JSONArray()),n->{unknownSeasonFetches.incrementAndGet();return requestedSeason;},1000).isEmpty()&&unknownSeasonFetches.get()==0,"Missing requested availability must remain on its own details, never replace it with an unrelated playable season");checks++;
        System.out.println("Native model contracts passed: "+checks);
        for(String arg:args)if(arg.equals("--episodes-live")){
            for(int liveId:new int[]{20,154587,269}){JSONObject liveSummary=NativeDiscovery.detail(liveId),secondary=NativeEpisodes.load(liveId,liveSummary);NativeSeasons.apply(secondary,null);cached.put(liveId,secondary);org.json.JSONArray liveEpisodes=secondary.getJSONArray("episodeList");check(liveEpisodes.length()>0,"Secondary availability must contain actual episodes");decode("com.ellation.crunchyroll.model.Episode",NativeCatalog.episode(secondary,liveEpisodes.getJSONObject(0)));NativePlayback.publicHttps(liveEpisodes.getJSONObject(0).getString("thumbnail"));JSONObject nativeList=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/seasons/ANI"+liveId+"S1/episodes"));check(nativeList.getJSONArray("data").length()>0,"Secondary episodes must navigate through original season routes");System.out.println("Live secondary episodes passed: AniList "+liveId+", "+liveEpisodes.length()+" episodes, exact source IDs and real episode image");}
        }
        for(String arg:args)if(arg.equals("--franchise-live")){
            JSONObject categories=NativeDiscovery.categories();org.json.JSONArray genres=categories.getJSONArray("data");
            check(genres.length()==17,"All genre routes retained");
            for(int i=0;i<genres.length();i++){
                JSONObject genre=genres.getJSONObject(i);Object original=decode("com.ellation.crunchyroll.model.categories.Category",genre);check(!((java.util.List<?>)call(original,"getBackgrounds")).isEmpty(),"Real genre artwork missing for "+genre.getString("id"));
                JSONObject filtered=NativeDiscovery.route(android.net.Uri.parse("https://local/browse?categories="+genre.getString("id")+"&start=0&n=3"));
                org.json.JSONArray entries=filtered.getJSONArray("data");check(entries.length()>0,"Genre list empty for "+genre.getString("id"));
                String expectedGenre=genre.getJSONObject("localization").getString("title");for(int j=0;j<entries.length();j++){JSONObject cachedTitle=BackendBridge.cachedTitle(Integer.parseInt(entries.getJSONObject(j).getString("id").substring(3)));boolean contains=false;org.json.JSONArray labels=cachedTitle.getJSONArray("genres");for(int g=0;g<labels.length();g++)if(expectedGenre.equals(labels.getString(g)))contains=true;check(contains,"Genre route lost its filter");}
            }
            System.out.println("Live genres passed: 17 artwork models and 17 nonempty correctly filtered lists");
            JSONObject search=NativeDiscovery.route(android.net.Uri.parse("https://local/search?q=one%20punch%20man&n=25"));org.json.JSONArray cards=search.getJSONArray("data").getJSONObject(0).getJSONArray("items");int matching=0;for(int i=0;i<cards.length();i++)if(cards.getJSONObject(i).getString("id").equals("ANI21087"))matching++;check(matching==1,"One-Punch Man root must have one grouped search card");
            JSONObject group=NativeFranchises.series(21087);check(NativeSeasons.numbers(group).size()==3,"One-Punch Man must expose three available seasons");
            for(int season=1;season<=3;season++){JSONObject list=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/seasons/ANI21087S"+season+"/episodes"));org.json.JSONArray eps=list.getJSONArray("data");check(eps.length()>0,"Season has no episodes");String asset=eps.getJSONObject(0).getString("id");int expected=season==1?21087:season==2?97668:153800;check(asset.equals("ANI"+expected+"E1"),"Wrong first source episode for season "+season);JSONObject ep=NativeCatalog.route(android.net.Uri.parse("https://local/content/v2/cms/episodes/"+asset));check(ep.getJSONArray("data").getJSONObject(0).getString("season_id").equals("ANI21087S"+season),"Episode click lost its group");System.out.println("Season "+season+": "+eps.length()+" real episodes, first source "+asset);}
            JSONObject playback=NativePlayback.resolve("ANI21087E1");String downloadHls=playback.getJSONObject("streams").getJSONObject("adaptive_hls").getJSONObject("").getString("url");String chosen=NativeDownloads.variant(downloadHls,NativePlayback.get(downloadHls,NativePlayback.REFERER),360);NativeDownloads.validate(NativePlayback.get(chosen,NativePlayback.REFERER));
            System.out.println("Live non-DRM HLS download manifest passed; One-Punch Man E1 subtitle locales: "+playback.getJSONObject("subtitles").names());
        }
        for(String arg:args)if(arg.equals("--catalog-live")){
            JSONObject one=NativeDiscovery.route(android.net.Uri.parse("https://local/browse?start=0&n=25")),two=NativeDiscovery.route(android.net.Uri.parse("https://local/browse?start=25&n=25"));
            java.util.HashSet<String> ids=new java.util.HashSet<>();for(int i=0;i<one.getJSONArray("data").length();i++)ids.add(one.getJSONArray("data").getJSONObject(i).getString("id"));
            for(int i=0;i<two.getJSONArray("data").length();i++)check(ids.add(two.getJSONArray("data").getJSONObject(i).getString("id")),"Catalog pages repeat title IDs");
            JSONObject three=NativeDiscovery.route(android.net.Uri.parse("https://local/browse?start=50&n=25"));
            for(int i=0;i<three.getJSONArray("data").length();i++)check(ids.add(three.getJSONArray("data").getJSONObject(i).getString("id")),"Catalog provider page boundary repeats title IDs");
            check(one.getJSONArray("data").length()==25&&two.getJSONArray("data").length()==25,"Catalog page lengths");
            JSONObject home=NativeHomeFeed.home(0,6);int homeTotal=home.getInt("total");java.util.Set<String> rowIds=new java.util.HashSet<>(),cards=new java.util.HashSet<>();int rows=0;
            for(int offset=0;offset<homeTotal;offset+=6){JSONObject chunk=NativeHomeFeed.home(offset,6);check(chunk.getInt("total")==homeTotal,"Home snapshot total changed while paging");org.json.JSONArray data=chunk.getJSONArray("data");
                for(int n=0;n<data.length();n++){JSONObject row=data.getJSONObject(n);check(rowIds.add(row.getString("id")),"Home repeats a row across native pages");
                    Object original=decode("com.ellation.crunchyroll.api.model.HomeFeedItemRaw",row);check((Boolean)call(original,"isValid"),"Live Home row invalid in original model");
                    if(row.optString("resource_type").equals("CURATED_COLLECTION")){rows++;org.json.JSONArray members=row.getJSONArray("ids");check(members.length()<=14,"Home rail exceeds image-work budget");for(int n2=0;n2<members.length();n2++)check(cards.add(members.getString(n2)),"Home repeats anime cards across collections");}
                }
            }
            check(rows>=8&&cards.size()>=60&&NativeHomeFeed.home(homeTotal,6).getJSONArray("data").length()==0,"Live Home must contain diverse rows and terminate cleanly: rows="+rows+", cards="+cards.size());
            System.out.println("Live Home passed: "+rows+" unique rails, "+cards.size()+" distinct cards, stable paging");
            cached.remove(154587);JSONObject detail=BackendBridge.series(154587);decode("com.ellation.crunchyroll.model.Panel",BackendBridge.panel(detail));
            if(detail.optBoolean("_availabilityUnknown"))System.out.println("Live details metadata retained; episode availability blocked/unavailable, episode-image check not performed");
            else{NativePlayback.publicHttps(NativeMetadata.string(detail.getJSONArray("episodeList").getJSONObject(0),"thumbnail"));System.out.println("Live episode image mapping passed");}
            JSONObject ranges=NativePlayback.skipEvents("ANI21E1");check(ranges.has("intro"),"Live intro metadata");
            System.out.println("Live hybrid catalog passed: disjoint pages, valid title model, intro metadata");
        }
        for(String arg:args)if(arg.equals("--stream-live")){
            JSONObject live=NativePlayback.resolve("ANI21E1");
            check(NativePlayback.mapHls("ANI21E1",decode("com.ellation.crunchyroll.api.cms.model.streams.Streams",live),null,"")!=null,"Live provider must map into original player");
            System.out.println("Live HLS resolver passed: One Piece episode 1 sub (manifest and model only)");
        }
        for(String arg:args)if(arg.equals("--subtitles-live")){
            JSONObject bundle=new JSONObject(NativePlayback.get("https://anivexaapi-aniko2.hf.space/api/watch/154587/sub/1",null)).getJSONObject("ssub");
            org.json.JSONArray tracks=bundle.getJSONArray("subtitles");java.util.HashSet<String> verified=new java.util.HashSet<>();
            for(int i=0;i<tracks.length();i++){JSONObject track=tracks.getJSONObject(i);String language=NativeSubtitles.locale(track);if(language.equals("es-ES")||language.equals("es-419")||language.equals("en-US")){String converted=NativeSubtitles.toAss(NativePlayback.get(track.getString("file"),NativePlayback.REFERER));check(converted.contains("Dialogue: 0,"),"Subtitle conversion must produce timed cues");verified.add(language);}}
            check(verified.contains("es-ES")&&verified.contains("es-419")&&verified.contains("en-US"),"Live Spanish variants and English tracks required for this fixture");
            System.out.println("Live subtitles passed: Frieren episode 1 English, Spanish and Latin American Spanish fetched and converted to ASS");
        }
        if(args.length>0&&args[0].equals("--cloud-negative")){
            try{CloudSession.signIn("native-contract@example.invalid","invalid-contract-password");throw new AssertionError("Unknown cloud user must not authenticate");}
            catch(BackendBridge.HttpFailure expected){check(expected.status==400||expected.status==401,"Auth must reject invalid credentials");}
            check(CloudSession.userId().isEmpty(),"Rejected login must not create a session");
            Method request=CloudSession.class.getDeclaredMethod("request",String.class,String.class,JSONObject.class,String.class);request.setAccessible(true);
            try{request.invoke(null,"/rest/v1/account_state?select=*","GET",null,null);throw new AssertionError("Public client key must not read private profiles");}
            catch(java.lang.reflect.InvocationTargetException expected){check(expected.getCause() instanceof BackendBridge.HttpFailure,"Expected explicit private-data rejection");int status=((BackendBridge.HttpFailure)expected.getCause()).status;check(status==401||status==403,"Private snapshots must reject unauthenticated access");}
            System.out.println("Live Supabase rejection checks passed: 2");
        }
    }
}
